USE master;
GO

DROP DATABASE IF EXISTS Lab6;
GO

CREATE DATABASE Lab6
ON ( NAME = Lab6_dat,
     FILENAME = '/var/opt/mssql/data/Lab6_dat.mdf',
     SIZE = 10MB,
     MAXSIZE = UNLIMITED,
     FILEGROWTH = 5%
)
LOG ON ( NAME = Lab6_log,
         FILENAME = '/var/opt/mssql/data/Lab6_log.ldf',
         SIZE = 5MB,
         MAXSIZE = 25MB,
         FILEGROWTH = 5MB
);
GO

USE Lab6;
GO

DROP TABLE IF EXISTS dbo.AIRCRAFT_SetDefault;
DROP TABLE IF EXISTS dbo.AIRCRAFT_SetNull;
DROP TABLE IF EXISTS dbo.AIRCRAFT_Cascade;
DROP TABLE IF EXISTS dbo.AIRCRAFT_NoAction;
DROP TABLE IF EXISTS dbo.AIRPORT_SEQ;
DROP TABLE IF EXISTS dbo.AIRPORT_GUID;
DROP TABLE IF EXISTS dbo.AIRLINE;
DROP SEQUENCE IF EXISTS dbo.Seq_AirportID;
GO

CREATE TABLE dbo.AIRLINE
(
    AirlineID INT IDENTITY(1,1) PRIMARY KEY,
    IATA CHAR(2) NOT NULL,
    ICAO CHAR(3) NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Country NVARCHAR(100) NOT NULL CONSTRAINT DF_AIRLINE_Country DEFAULT (N'Unknown'),
    CONSTRAINT AK_AIRLINE_IATA UNIQUE (IATA),
    CONSTRAINT AK_AIRLINE_ICAO UNIQUE (ICAO),
    CONSTRAINT CK_AIRLINE_IATA CHECK (IATA NOT LIKE '%[^A-Z]%'),
    CONSTRAINT CK_AIRLINE_ICAO CHECK (ICAO NOT LIKE '%[^A-Z]%')
);
GO

CREATE TABLE dbo.AIRPORT_GUID
(
    AirportID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
    IATA CHAR(3) NOT NULL CONSTRAINT AK_AIRPORT_GUID_IATA UNIQUE,
    ICAO CHAR(4) NOT NULL CONSTRAINT AK_AIRPORT_GUID_ICAO UNIQUE,
    Name NVARCHAR(100) NOT NULL,
    City NVARCHAR(100) NOT NULL,
    Timezone NVARCHAR(50) NOT NULL CONSTRAINT DF_AIRPORT_GUID_Timezone DEFAULT (N'UTC'),
    CONSTRAINT CK_AIRPORT_GUID_IATA CHECK (IATA NOT LIKE '%[^A-Z]%'),
    CONSTRAINT CK_AIRPORT_GUID_ICAO CHECK (ICAO NOT LIKE '%[^A-Z]%')
);
GO

CREATE SEQUENCE dbo.Seq_AirportID AS BIGINT START WITH 1 INCREMENT BY 1;
GO

CREATE TABLE dbo.AIRPORT_SEQ
(
    AirportID BIGINT NOT NULL DEFAULT NEXT VALUE FOR dbo.Seq_AirportID PRIMARY KEY,
    IATA CHAR(3) NOT NULL CONSTRAINT AK_AIRPORT_SEQ_IATA UNIQUE,
    ICAO CHAR(4) NOT NULL CONSTRAINT AK_AIRPORT_SEQ_ICAO UNIQUE,
    Name NVARCHAR(100) NOT NULL,
    City NVARCHAR(100) NOT NULL,
    Timezone NVARCHAR(50) NOT NULL CONSTRAINT DF_AIRPORT_SEQ_Timezone DEFAULT (N'UTC'),
    CONSTRAINT CK_AIRPORT_SEQ_IATA CHECK (IATA NOT LIKE '%[^A-Z]%'),
    CONSTRAINT CK_AIRPORT_SEQ_ICAO CHECK (ICAO NOT LIKE '%[^A-Z]%')
);
GO

CREATE TABLE dbo.AIRCRAFT_NoAction
(
    AircraftID INT IDENTITY(1,1) PRIMARY KEY,
    TailNumber NVARCHAR(50) NOT NULL,
    Model NVARCHAR(100) NOT NULL,
    SeatCapacity INT NOT NULL
        CONSTRAINT DF_AIRCRAFT_NoAction_Seat DEFAULT (100)
        CONSTRAINT CK_AIRCRAFT_NoAction_Seat CHECK (SeatCapacity > 0),
    AirlineID INT NULL,
    CONSTRAINT FK_AIRCRAFT_NoAction_AIRLINE FOREIGN KEY (AirlineID)
        REFERENCES dbo.AIRLINE(AirlineID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
GO

CREATE TABLE dbo.AIRCRAFT_Cascade
(
    AircraftID INT IDENTITY(1,1) PRIMARY KEY,
    TailNumber NVARCHAR(50) NOT NULL,
    Model NVARCHAR(100) NOT NULL,
    SeatCapacity INT NOT NULL
        CONSTRAINT DF_AIRCRAFT_Cascade_Seat DEFAULT (100)
        CONSTRAINT CK_AIRCRAFT_Cascade_Seat CHECK (SeatCapacity > 0),
    AirlineID INT NULL,
    CONSTRAINT FK_AIRCRAFT_Cascade_AIRLINE FOREIGN KEY (AirlineID)
        REFERENCES dbo.AIRLINE(AirlineID) ON DELETE CASCADE ON UPDATE NO ACTION
);
GO

CREATE TABLE dbo.AIRCRAFT_SetNull
(
    AircraftID INT IDENTITY(1,1) PRIMARY KEY,
    TailNumber NVARCHAR(50) NOT NULL,
    Model NVARCHAR(100) NOT NULL,
    SeatCapacity INT NOT NULL
        CONSTRAINT DF_AIRCRAFT_SetNull_Seat DEFAULT (100)
        CONSTRAINT CK_AIRCRAFT_SetNull_Seat CHECK (SeatCapacity > 0),
    AirlineID INT NULL,
    CONSTRAINT FK_AIRCRAFT_SetNull_AIRLINE FOREIGN KEY (AirlineID)
        REFERENCES dbo.AIRLINE(AirlineID) ON DELETE SET NULL ON UPDATE NO ACTION
);


CREATE TABLE dbo.AIRCRAFT_SetDefault
(
    AircraftID INT IDENTITY(1,1) PRIMARY KEY,
    TailNumber NVARCHAR(50) NOT NULL,
    Model NVARCHAR(100) NOT NULL,
    SeatCapacity INT NOT NULL
        CONSTRAINT DF_AIRCRAFT_SetDefault_Seat DEFAULT (100)
        CONSTRAINT CK_AIRCRAFT_SetDefault_Seat CHECK (SeatCapacity > 0),
    AirlineID INT NOT NULL DEFAULT 1,
    CONSTRAINT FK_AIRCRAFT_SetDefault_AIRLINE FOREIGN KEY (AirlineID)
        REFERENCES dbo.AIRLINE(AirlineID) ON DELETE SET DEFAULT ON UPDATE NO ACTION
);
GO

INSERT INTO dbo.AIRLINE (IATA, ICAO, Name, Country)
VALUES ('ZZ','ZZZ',N'Default Airline',N'-');
GO
INSERT INTO dbo.AIRLINE (IATA, ICAO, Name, Country)
VALUES ('SU','AFL',N'Aeroflot',N'Russia');
GO
INSERT INTO dbo.AIRLINE (IATA, ICAO, Name, Country)
VALUES ('UT','UTA',N'UTair',N'Russia');
GO
SELECT SCOPE_IDENTITY() AS LastInsertedAirlineID;
GO

INSERT INTO dbo.AIRPORT_GUID (IATA, ICAO, Name, City, Timezone)
VALUES ('SVO','UUEE',N'Sheremetyevo',N'Moscow',N'Europe/Moscow');
GO
INSERT INTO dbo.AIRPORT_SEQ (IATA, ICAO, Name, City, Timezone)
VALUES ('DME','UUDD',N'Domodedovo',N'Moscow',N'Europe/Moscow');
GO

INSERT INTO dbo.AIRCRAFT_NoAction (TailNumber, Model, SeatCapacity, AirlineID)
VALUES (N'RA-001', N'Model A', 120, 1);
GO
INSERT INTO dbo.AIRCRAFT_Cascade (TailNumber, Model, SeatCapacity, AirlineID)
VALUES (N'RA-002', N'Model B', 150, 1);
GO
INSERT INTO dbo.AIRCRAFT_SetNull (TailNumber, Model, SeatCapacity, AirlineID)
VALUES (N'RA-003', N'Model C', 100, 1);
GO
INSERT INTO dbo.AIRCRAFT_SetDefault (TailNumber, Model, SeatCapacity)
VALUES (N'RA-004', N'Model D', 180);
GO

SELECT * FROM dbo.AIRLINE;
SELECT * FROM dbo.AIRPORT_GUID;
SELECT * FROM dbo.AIRPORT_SEQ;
SELECT * FROM dbo.AIRCRAFT_NoAction;
SELECT * FROM dbo.AIRCRAFT_Cascade;
SELECT * FROM dbo.AIRCRAFT_SetNull;
SELECT * FROM dbo.AIRCRAFT_SetDefault;
GO
