USE Lab10;
GO

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRANSACTION
SELECT *
FROM dbo.AIRCRAFT
WHERE TailNumber = N'RA-001';
WAITFOR DELAY '00:00:07';
SELECT *
FROM dbo.AIRCRAFT
WHERE TailNumber = N'RA-001';
COMMIT TRANSACTION;
GO

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION
SELECT *
FROM dbo.AIRCRAFT
WHERE TailNumber = N'RA-002';
WAITFOR DELAY '00:00:07';
SELECT *
FROM dbo.AIRCRAFT
WHERE TailNumber = N'RA-002';
COMMIT TRANSACTION;
GO

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
BEGIN TRANSACTION
SELECT *
FROM dbo.AIRCRAFT
WHERE SeatCapacity > 150;
WAITFOR DELAY '00:00:07';
SELECT *
FROM dbo.AIRCRAFT
WHERE SeatCapacity > 150;
COMMIT TRANSACTION;
GO

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRANSACTION
SELECT *
FROM dbo.AIRCRAFT
WHERE SeatCapacity > 150;
WAITFOR DELAY '00:00:07';
SELECT *
FROM dbo.AIRCRAFT
WHERE SeatCapacity > 150;
COMMIT TRANSACTION;
GO
