USE master;
GO

IF DB_ID(N'Lab5') IS NOT NULL
BEGIN
  ALTER DATABASE Lab5 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
END
DROP DATABASE IF EXISTS Lab5;
GO

-- TASK 1
CREATE DATABASE Lab5
ON ( NAME = N'Lab5_dat',
     FILENAME = N'/var/opt/mssql/data/Lab5_dat.mdf',
     SIZE = 64MB,
     MAXSIZE = UNLIMITED,
     FILEGROWTH = 64MB )
LOG ON ( NAME = N'Lab5_log',
     FILENAME = N'/var/opt/mssql/data/Lab5_log.ldf',
     SIZE = 32MB,
     MAXSIZE = 2048MB,
     FILEGROWTH = 32MB );
GO

-- TASK 2
USE Lab5;
GO

DROP TABLE IF EXISTS dbo.AIRPORT;
GO

CREATE TABLE dbo.AIRPORT
(
  AirportID INT           NOT NULL PRIMARY KEY,
  IATA      CHAR(3)       NOT NULL UNIQUE,
  ICAO      CHAR(4)       NOT NULL UNIQUE,
  Name      NVARCHAR(100) NOT NULL,
  City      NVARCHAR(100) NOT NULL,
  Timezone  NVARCHAR(50)  NOT NULL
);
GO

SELECT TOP (0) * FROM dbo.AIRPORT;
GO

-- TASK 3
ALTER DATABASE Lab5 ADD FILEGROUP AppDataFG;
GO
ALTER DATABASE Lab5 ADD FILE
(
  NAME = N'Lab5_AppData',
  FILENAME = N'/var/opt/mssql/data/Lab5_appdata.ndf',
  SIZE = 32MB,
  MAXSIZE = 512MB,
  FILEGROWTH = 32MB
) TO FILEGROUP AppDataFG;
GO

-- TASK 4
ALTER DATABASE Lab5 MODIFY FILEGROUP AppDataFG DEFAULT;
GO

-- TASK 5
DROP TABLE IF EXISTS dbo.AIRLINE;
GO

CREATE TABLE dbo.AIRLINE
(
  AirlineID INT           NOT NULL PRIMARY KEY,
  IATA      CHAR(2)       NOT NULL UNIQUE,
  ICAO      CHAR(3)       NOT NULL UNIQUE,
  Name      NVARCHAR(100) NOT NULL,
  Country   NVARCHAR(100) NOT NULL
)
ON AppDataFG;
GO

SELECT TOP (0) * FROM dbo.AIRLINE;
GO

-- TASK 6
ALTER DATABASE Lab5 MODIFY FILEGROUP [PRIMARY] DEFAULT;
GO
DROP TABLE IF EXISTS dbo.AIRLINE;
GO
ALTER DATABASE Lab5 REMOVE FILE Lab5_AppData;
GO
ALTER DATABASE Lab5 REMOVE FILEGROUP AppDataFG;
GO

-- TASK 7
DROP SCHEMA IF EXISTS AviationSchema;
GO

CREATE SCHEMA AviationSchema;
GO

ALTER SCHEMA AviationSchema TRANSFER dbo.AIRPORT;
GO

DROP TABLE IF EXISTS AviationSchema.AIRPORT;
GO

DROP SCHEMA IF EXISTS AviationSchema;
GO
